export const API_BASE = 'http://145.241.168.3:8000';

export const OVERPASS_CATS = new Set(['cinema', 'musee']);
export const BACKEND_CATS  = new Set(['musique', 'exposition', 'vide-grenier', 'spectacle', 'atelier', 'restaurant', 'cafe', 'bar', 'brocante', 'sport', 'popup', 'boutique', 'rooftop', 'marche', 'loisirs', 'autre']);

export const CAT_COLORS = {
  cinema:         '#E8503E',
  musee:          '#C9A84C',
  musique:        '#E8503E',
  exposition:     '#9B7EC8',
  spectacle:      '#D4825A',
  atelier:        '#5BAFBF',
  restaurant:     '#D4825A',
  cafe:           '#A0784A',
  bar:            '#C9784A',
  brocante:       '#7EB5A6',
  'vide-grenier': '#7EB5A6',
  sport:          '#4CAF50',
  popup:          '#E8A03E',
  boutique:       '#B07EC8',
  rooftop:        '#5BAFBF',
  marche:         '#7EB5A6',
  loisirs:        '#4CAF50',
  autre:          '#888888',
};

export const CAT_EMOJI = {
  cinema:         '🎬',
  musee:          '🏛',
  musique:        '🎵',
  exposition:     '🖼',
  spectacle:      '🎭',
  atelier:        '🎨',
  restaurant:     '🍽',
  cafe:           '☕',
  bar:            '🍺',
  brocante:       '🪑',
  'vide-grenier': '🪑',
  sport:          '🏃',
  popup:          '🛍',
  boutique:       '🛍',
  rooftop:        '🌇',
  marche:         '🚶',
  loisirs:        '🎡',
  autre:          '📌',
};

export const SOURCE_LABELS = {
  'lebonbon_food':    'LeBonbon',
  'lebonbon_drinks':  'LeBonbon',
  'lebonbon_news':    'LeBonbon',
  'lebonbon_healthy': 'LeBonbon',
  'lebonbon_loisirs': 'LeBonbon',
  'sortiraparis':     'Sortir à Paris',
  'sortiraparis_restaurant': 'SortirAParis Restos',
  'sortiraparis_cafes':      'SortirAParis Cafés',
  'sortiraparis_expos':      'SortirAParis Expos',
  'sortiraparis_popup':      'SortirAParis Popup',
  'timeout_paris':    'Time Out Paris',
  'paris_opendata':   'Paris Opendata',
  'paris_fr':         'Paris.fr',
  'parisbouge_bars':  'ParisBouge',
  'parisbouge_restos':'ParisBouge',
  'parisbouge_expos': 'ParisBouge',
  'newtable':         'NewTable',
  'inpi_food':        'INPI',
  'inpi_drinks':      'INPI',
  'numero_popup':     'Numéro',
  'secrets_of_paris': 'Secrets of Paris',
  'parismusee_expos': 'Paris Musées',
  'OpenStreetMap':    'OpenStreetMap',
};

export const ALL_CATS = [
  { cat: 'musique',      emoji: '🎵', label: 'Musique' },
  { cat: 'exposition',   emoji: '🖼', label: 'Expo' },
  { cat: 'restaurant',   emoji: '🍽', label: 'Restaurant' },
  { cat: 'bar',          emoji: '🍺', label: 'Bar' },
  { cat: 'cafe',         emoji: '☕', label: 'Café' },
  { cat: 'rooftop',      emoji: '🌇', label: 'Rooftop' },
  { cat: 'popup',        emoji: '🛍', label: 'Pop-up' },
  { cat: 'boutique',     emoji: '🏪', label: 'Boutique' },
  { cat: 'wellness',     emoji: '🧘', label: 'Wellness' },
  { cat: 'spectacle',    emoji: '🎭', label: 'Spectacle' },
  { cat: 'cinema',       emoji: '🎬', label: 'Cinéma' },
  { cat: 'musee',        emoji: '🏛', label: 'Musée' },
  { cat: 'marche',       emoji: '🛒', label: 'Marché' },
  { cat: 'brocante',     emoji: '🪑', label: 'Brocante' },
  { cat: 'vide-grenier', emoji: '🪑', label: 'Vide-grenier' },
  { cat: 'sport',        emoji: '🏃', label: 'Sport' },
  { cat: 'atelier',      emoji: '🎨', label: 'Atelier' },
  { cat: 'loisirs',      emoji: '🎡', label: 'Loisirs' },
  { cat: 'autre',        emoji: '📌', label: 'Autre' },
];

export const _PARIS_POLY = [
  [48.9022, 2.3084],[48.8985, 2.3650],[48.8855, 2.4050],
  [48.8650, 2.4175],[48.8450, 2.4175],[48.8300, 2.3780],
  [48.8195, 2.3311],[48.8242, 2.2857],[48.8395, 2.2535],
  [48.8572, 2.2350],[48.8789, 2.2600],[48.9022, 2.3084],
];
